import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 style={{marginBottom: "10px"}}>Employee App</h1>
      <h3>This app gives information about our employees</h3>
      <p>Click Here -&gt; <Link href="/employee"><a>App Link</a></Link></p>
    </div>
  )
}
